name: habit_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animated_splash_screen: ^1.3.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.1.0
  get: ^4.7.2
  get_storage: ^2.1.1
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  table_calendar: ^3.2.0
  timezone: ^0.10.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
